/**
 * Universal Header Injector for Sentinel Peak Solutions
 * Ensures consistent navigation across all pages with automatic active page detection
 * Compatible with GoHighLevel and static HTML implementations
 */

class UniversalHeader {
    constructor() {
        this.currentPage = this.getCurrentPage();
        this.navigationData = {
            brandName: 'Sentinel Peak Solutions',
            logoSrc: 'images/sentinel-peak-logo.png',
            logoAlt: 'Sentinel Peak Solutions - Digital Solutions for Local Businesses',
            phone: '(559) 245-6571',
            location: 'Fresno, CA • Central Valley',
            links: [
                { href: 'index.html', text: 'Home', page: 'index' },
                { href: 'services.html', text: 'Services', page: 'services' },
                { href: 'portfolio.html', text: 'Portfolio', page: 'portfolio' },
                { href: 'about.html', text: 'About', page: 'about' },
                { href: 'contact.html', text: 'Contact', page: 'contact' },
                { href: 'contact.html', text: 'Contact Us', page: 'contact' }
            ]
        };
        
        this.init();
    }
    
    /**
     * Determine current page from URL
     */
    getCurrentPage() {
        const path = window.location.pathname;
        const filename = path.split('/').pop() || 'index.html';
        
        // Handle different page naming conventions
        if (filename === '' || filename === 'index.html' || filename === '/') {
            return 'index';
        }
        
        // Extract page name without extension
        return filename.replace('.html', '');
    }
    
    /**
     * Generate navigation HTML structure
     */
    generateNavigationHTML() {
        const desktopLinks = this.navigationData.links.map(link => {
            const isActive = link.page === this.currentPage;
            const activeClass = isActive ? ' active' : '';
            const ariaCurrent = isActive ? ' aria-current="page"' : '';
            const target = link.external ? ' target="_blank" rel="noopener"' : '';
            
            if (link.external && link.page === 'booking') {
                return `
                    <li role="none">
                        <a href="${link.href}" class="btn btn-primary" role="menuitem"${target}>${link.text}</a>
                    </li>
                `;
            } else {
                return `
                    <li role="none">
                        <a href="${link.href}" class="nav-link${activeClass}" role="menuitem"${ariaCurrent}${target}>${link.text}</a>
                    </li>
                `;
            }
        }).join('');
        
        const mobileLinks = this.navigationData.links.map(link => {
            const target = link.external ? ' target="_blank" rel="noopener"' : '';
            return `
                <li role="none">
                    <a href="${link.href}" class="mobile-nav-link" role="menuitem"${target}>${link.text}</a>
                </li>
            `;
        }).join('');
        
        return `
            <!-- UNIVERSAL HEADER COMPONENT (Generated by js/header.js) -->
            <div class="nav-wrapper" id="navbar">
                <nav class="navbar container">
                    <!-- Brand Container: Logo Left + Company Name Center -->
                    <div class="brand-container">
                        <a href="index.html" class="logo" aria-label="${this.navigationData.brandName} Home">
                            <img src="${this.navigationData.logoSrc}" 
                                 alt="${this.navigationData.logoAlt}" 
                                 class="logo-image"
                                 loading="lazy">
                        </a>
                        <span class="company-name">${this.navigationData.brandName}</span>
                    </div>
                    
                    <!-- Desktop Navigation Menu (Hidden on Mobile) -->
                    <ul class="nav-menu" role="menubar">
                        ${desktopLinks}
                    </ul>
                    
                    <!-- Hamburger Menu Button (Visible on Mobile) -->
                    <button class="hamburger-menu" 
                            id="hamburger-menu" 
                            aria-label="Toggle mobile navigation menu"
                            aria-expanded="false"
                            aria-controls="mobile-menu"
                            type="button">
                        <span class="hamburger-line" aria-hidden="true"></span>
                        <span class="hamburger-line" aria-hidden="true"></span>
                        <span class="hamburger-line" aria-hidden="true"></span>
                    </button>
                </nav>
            </div>

            <!-- Mobile Menu Overlay -->
            <div class="mobile-menu" 
                 id="mobile-menu" 
                 role="dialog" 
                 aria-modal="true" 
                 aria-labelledby="mobile-menu-title"
                 aria-hidden="true">
                
                <div class="mobile-menu-content">
                    <!-- Mobile Menu Header -->
                    <div class="mobile-menu-header">
                        <h2 class="mobile-menu-title" id="mobile-menu-title">Navigation</h2>
                        <p class="mobile-menu-subtitle">Digital Solutions for Local Businesses</p>
                    </div>
                    
                    <!-- Mobile Navigation Links -->
                    <nav class="mobile-navigation" role="navigation" aria-label="Mobile menu">
                        <ul class="mobile-nav-links" role="menubar">
                            ${mobileLinks}
                        </ul>
                    </nav>
                    
                    <!-- Mobile Menu Footer -->
                    <div class="mobile-menu-footer">
                        <div class="mobile-contact-info">
                            <a href="tel:+15592456571" class="mobile-phone">${this.navigationData.phone}</a>
                            <p class="mobile-location">${this.navigationData.location}</p>
                        </div>
                    </div>
                </div>
            </div>
        `;
    }
    
    /**
     * Inject navigation into page
     */
    injectNavigation() {
        // Try to find existing navigation container
        let navContainer = document.querySelector('.nav-wrapper, nav, #navbar, [class*="nav"]');
        
        if (!navContainer) {
            // If no navigation container found, create one and insert after body
            navContainer = document.createElement('div');
            document.body.insertBefore(navContainer, document.body.firstChild);
        }
        
        // Replace existing navigation with universal header
        navContainer.outerHTML = this.generateNavigationHTML();
        
        // Log successful injection for debugging
        console.log(`✅ Universal header injected successfully for page: ${this.currentPage}`);
    }
    
    /**
     * Handle GoHighLevel specific overrides
     */
    handleGoHighLevelOverrides() {
        // Check if GoHighLevel is present
        const isGoHighLevel = document.querySelector('[class*="ghl"], [id*="ghl"], script[src*="gohighlevel"]');
        
        if (isGoHighLevel) {
            console.log('🔧 GoHighLevel detected - applying compatibility overrides');
            
            // Add GoHighLevel compatibility class to body
            document.body.classList.add('ghl-compatible');
            
            // Force our navigation styles with higher specificity
            const ghlOverrideCSS = `
                <style id="ghl-nav-override">
                /* GoHighLevel Navigation Overrides */
                body.ghl-compatible .nav-wrapper {
                    position: fixed !important;
                    top: 0 !important;
                    width: 100% !important;
                    z-index: 9999 !important;
                    background: rgba(0, 0, 0, 0.95) !important;
                }
                
                body.ghl-compatible .hamburger-menu {
                    display: none !important;
                }
                
                @media (max-width: 768px) {
                    body.ghl-compatible .hamburger-menu {
                        display: flex !important;
                        background: rgba(255, 255, 255, 0.1) !important;
                        border: 2px solid rgba(255, 255, 255, 0.2) !important;
                    }
                    
                    body.ghl-compatible .nav-menu {
                        display: none !important;
                    }
                }
                </style>
            `;
            
            // Inject override styles
            document.head.insertAdjacentHTML('beforeend', ghlOverrideCSS);
        }
    }
    
    /**
     * Validate navigation elements are present
     */
    validateNavigation() {
        const requiredElements = [
            '#hamburger-menu',
            '#mobile-menu',
            '.nav-menu',
            '.mobile-nav-links'
        ];
        
        const missing = requiredElements.filter(selector => !document.querySelector(selector));
        
        if (missing.length > 0) {
            console.warn('⚠️ Missing navigation elements:', missing);
            return false;
        }
        
        console.log('✅ All navigation elements validated successfully');
        return true;
    }
    
    /**
     * Initialize universal header system
     */
    init() {
        // Wait for DOM to be ready
        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', () => this.setup());
        } else {
            this.setup();
        }
    }
    
    /**
     * Setup navigation after DOM is ready
     */
    setup() {
        try {
            // Inject navigation
            this.injectNavigation();
            
            // Handle GoHighLevel compatibility
            this.handleGoHighLevelOverrides();
            
            // Validate navigation elements
            this.validateNavigation();
            
            // Initialize mobile menu functionality after a brief delay
            // This ensures the navigation is fully rendered
            setTimeout(() => {
                if (window.sentinelAnimations && typeof window.sentinelAnimations.init === 'function') {
                    // Reinitialize animations if available
                    window.sentinelAnimations.init();
                }
            }, 100);
            
        } catch (error) {
            console.error('❌ Failed to initialize universal header:', error);
            
            // Fallback: Ensure basic navigation exists
            this.ensureFallbackNavigation();
        }
    }
    
    /**
     * Fallback navigation for error cases
     */
    ensureFallbackNavigation() {
        if (!document.querySelector('.nav-wrapper, nav')) {
            const fallbackNav = document.createElement('nav');
            fallbackNav.innerHTML = `
                <div style="background: #000; padding: 1rem; color: white; text-align: center;">
                    <strong>Sentinel Peak Solutions</strong> | 
                    <a href="index.html" style="color: #4ade80;">Home</a> | 
                    <a href="services.html" style="color: #4ade80;">Services</a> | 
                    <a href="contact.html" style="color: #4ade80;">Contact</a>
                </div>
            `;
            document.body.insertBefore(fallbackNav, document.body.firstChild);
            console.log('🔧 Fallback navigation activated');
        }
    }
}

// Auto-initialize when script loads
document.addEventListener('DOMContentLoaded', () => {
    window.universalHeader = new UniversalHeader();
});

// Also initialize immediately if DOM is already ready
if (document.readyState !== 'loading') {
    window.universalHeader = new UniversalHeader();
}

// Export for manual initialization if needed
window.UniversalHeader = UniversalHeader;